### PR TITLE
Forms-260 # Error summary scroll to needs to uncollapse subforms

### PR DESCRIPTION
**Pull request by simonmarklar**
- Updated subform element page to be the same as the parent form page
- Added global `element:focus` event

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Think it's worth documenting this event?

**Comment by simonmarklar** [comment]
yeah why not, I'll document all the other events FORMS uses as well as I cant find them in the docs folder

**Comment by simonmarklar** [comment]
I just found an event `BMP.Forms.trigger('behavioursExecuted');`. I think i'll update the `element:focus` event to trigger on `BMP.Forms` to keep things consistent and also to denote that the event is a FORMS specific event

**Comment by GeetaSajwan** [comment]
LGTM

**Pull request merged**
