### PR TITLE
FORMS-254 # Subform error not clearing for parent subform

### PR DESCRIPTION
**Pull request by simonmarklar**
- Removed useless and expensive 'This subform has errors' Error message
  - Moved `updateFieldErrors` function into `validate`
  - Fixed up tests that expected the `SUBFORM` error
- only `invalid` and `valid` events propagate up from subforms to parent form
  - fixed events that tested for `change:value`. They now check for the `valid` event.
  - added a guard in these events so that listener only executes when it is bound to the model that triggered the event.
- Changed views from `model#on` to `view#listenTo` so that views can clean up after themselves automatically

### CODE REVIEW

**Comment by simonmarklar** [comment]
Timings:

on average the timings appear to be the same as before, perhaps on slightly (a few ms) faster for some things. Ran the test 3 times, the first time for both branches with a cleared cache. However it should be noted that the develop branch does not show the 'SUBFORM' error correctly, which was the issue this pr is meant to address.

_test/27_1_generated/_

develop branch timings

chrome:
initialize, 186.579ms
preloadPromise, 186.938ms
append, 1.087ms
jQueryMobile enhance, 14.086ms
pageInjected, 194.919ms
add subForm31 x4, 825.936ms
add subForm64 x4, 759.215ms
turn to page[1], 1324.085ms

initialize: 126.998ms
preloadPromise: 127.274ms
append: 1.335ms
jQueryMobile enhance: 8.188ms
pageInjected: 194.683ms
add subForm31 x4: 685.429ms
add subForm64 x4: 615.771ms
turn to page[1]: 965.393ms

nitialize: 147.255ms
preloadPromise: 147.565ms
append: 1.249ms
jQueryMobile enhance: 10.166ms
pageInjected: 205.080ms
add subForm31 x4: 625.402ms
add subForm64 x4: 618.661ms
turn to page[1]: 999.116ms

FORMS-254 Branch

chrome:
initialize: 151.875ms
preloadPromise: 152.143ms
append: 1.068ms
jQueryMobile enhance: 12.409ms
pageInjected: 196.230ms
add subForm31 x4: 814.638ms
add subForm64 x4: 505.335ms
turn to page[1]: 1065.029ms

initialize: 161.391ms
preloadPromise: 161.856ms
append: 2.577ms
jQueryMobile enhance: 8.430ms
pageInjected: 189.998ms
add subForm31 x4: 661.456ms
add subForm64 x4: 582.544ms
turn to page[1]: 996.734ms

initialize: 168.539ms
preloadPromise: 168.819ms
append: 1.010ms
jQueryMobile enhance: 7.555ms
pageInjected: 195.125ms
add subForm31 x4: 778.929ms
add subForm64 x4: 600.577ms
turn to page[1]: 1040.862ms

**Comment by jokeyrhyme** [comment]
I was a little worried about no longer automatically falling back to `this.model` within `ElementView#renderErrors()`, but it _does_ look like all ways it can be called ensure that a model is the first argument. :+1:
Note: if this _is_ ever called without a model, then it will through an "undefined is not an object" error.

**Comment by simonmarklar** [comment]
UX review from sam, When we decided to remove the sub form field error

**Comment by jokeyrhyme** [comment]
LGTM :+1:

**Pull request merged**
