### PR TITLE
FORMS-243 # [CHORE] Update defaults property to be a function

### PR DESCRIPTION
**Pull request by simonmarklar**
- updated the defaults to be a function
- added tests to ensure that for every model that has a defaults proeprty, it is a function
- accidentally included the file exclusion regex. o well
- changed the naming of `Element` to `ElementModel` to avoid clashes with the global DOM constructor of the same name

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
As `.defaults()` returns a fresh Object each time, we don't need to guard against modifying the "original" object.

So instead of:

``` js
return _.assign({}, ElementModel.prototype.defaults.call(this), { /* ... */ });
```

we can probably just have:

``` js
return _.assign(ElementModel.prototype.defaults.call(this), { /* ... */ });
```

It also occurs to me that switching to methods now will ease our transition to ES2015 `class`, which lacks the ability to elegantly define properties that are _not_ functions. So good job! :)

**Comment by jokeyrhyme** [comment]
If you wanted to avoid some test boilerplate, you could probably just add the tests to the "17_main" suite, which has other tests that have nothing to do with form definitions.

**Comment by simonmarklar** [comment]
lol, I originally had it without the guard. I'll change it back over

i'll add the tests to 17_main, much better spot for it

**Comment by jokeyrhyme** [comment]
LGTM :+1:

**Comment by jokeyrhyme** [comment]
I'm wondering whether this counts as a compatibility-break? Anyone expecting `defaults` to be an Object is in for a surprise.

**Comment by simonmarklar** [comment]
hmmm technically yes

**Comment by jokeyrhyme** [comment]
We can probably just point at Backbone's documentation: http://backbonejs.org/#Model-defaults
Highlight that people following the upstream documentation are fine here.

**Comment by jokeyrhyme** [comment]
We technically haven't changed the way something is documented to work. Or a way we've encouraged people to use it in the past.

**Comment by simonmarklar** [comment]
yeah just slip it in and mention in the change log perhaps. not worth a version bump thats for sure

**Pull request merged**
