### PR TITLE
WIP FORMS-203 # perform validation asynchronously via a queue

### PR DESCRIPTION
**Pull request by jokeyrhyme**
## asynchronous validation queue
- calls to `#validate()` are debounced, only actually doing anything if not called in the last 500ms
- `#validate()` lodges an asynchronous job in the queue, does no actual validation itself
- validation queue only allows 10 jobs to be open at a time, and each job lasts at least 10ms
- new "validated" event on `window.BMP.Forms` event emitter is triggered when the queue is empty
## events
- new "valid" event joins the "invalid" event as being triggered when asynchronous validation is complete
- "valid" and "invalid" events bubble from elements to their form, and from sub-forms to their parent sub-form element
- `#validate()` is called whenever "value" attribute is set, event when there is no change, relying on debounce and queue to keep manageable
### MacBook Pro Retina-15 2012
- form appears in 2074ms, down from 3795ms (45% improvement)
- initial behaviours finished in 3071ms, up from 1725ms (78% longer delay)
- initial validation finished in 2887ms (previously blocked form appearing)
### Nexus 7 2012
- form appears in 37116ms, down from 74292ms (50% improvement)
- initial behaviours finished in 73469ms, up from 35201ms (109% longer delay)
- initial validation finished in 39412ms (previously blocked form appearing)

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Input latency improvements reviewed and confirmed by Sam.

**Comment by jokeyrhyme** [comment]
I’m concerned about the new delay introduced to the “behavioursExecuted” event. This is for an extreme case with lots of behaviours, but if you folks think this is a problem, I’m happy to go back and re-work this.

**Comment by simonmarklar** [comment]
I'm very happy that the model no longer double initializes the view!

There are a few changes that you have made that make me wonder about the impact of async validation on input latency. For example initialising and rendering the error summary view would of been expensive on a mobile, it would be interesting to see what the timing of changing the rendering only is. oh well its obviously running faster now :+1: 

Obviously running the validation debounced means less cpu usage and faster, but now we have the problem that for a few hundred milliseconds, the model's validation state and value are not in sync . Its one more async thing that we have to deal with. I dont know how much of an issue this would be though and I do think though that the boost in start up time is well worth it. Time to boot can really effect how people view your app. _shrug_

One thing that I realized today when sam mentioned how previous validation worked, was that now we dont support IE8 (and please say 9 as well ;), the HTML 5 Forms validation api is [available](http://caniuse.com/#feat=form-validation)... i wonder if that can be harnessed for even more speed?

**Comment by jokeyrhyme** [comment]
Good thinking about HTML5 Form Validation. Dropping IE8 doesn't solve everything though: http://caniuse.com/#feat=form-validation

I do think there's opportunity to detect support and switch to a "native speed" validation where possible. That'll be separate work to this.

I also agree with your concerns about value and validation results no longer matching up synchronously. It'll be interesting to see how much this is a problem for solution developers.

**Comment by simonmarklar** [comment]
Hmmm. it feels like its getting complicated. eg should `Model#val()` also return a promise that resolves when the model is validated? will waiting for validation to be finished  in `setRecord` make the page load up but then external errors suddenly appear on forms that take a while to resolve all the queued validations? should we be recommending that everyone listens to the validation finished event from now on?? feels like a can of worms

in the case of `setRecord`, I would leave it how it is and change the BIC to listen to the completed validation event and then setExternalErrors

You did quite a few changes that definitely helped with speed, looking over the changes makes things like the how i did the error list DOM manipulations, re-writing the html and probably causing reflows nearly every keypress seem really wasteful, far more wasteful than the roughly 4 greater than and one exists check most elements have. . I guess i'm still very doubtful that the actual validation (which is , in most cases, less than 15 lines and a simple equality or greater than/less than check) is the cause of slowdown, especially with the added complexity of dealing with async model validation and im worried that this is going to be a problem down the track.

but we can deal with those problems when they arise, if they arise. perhaps im just over thinking this :)

**Comment by jokeyrhyme** [comment]
I don't think you're over thinking this at all. The load time is improved by delaying the validation, and the input latency is improved by debouncing it. Queuing the validation is not strictly necessary for this, but even without the queue (perhaps) over-complicating it, the validation is still delayed.

Who actually needs to know when validation is complete?
- anyone / anything merging in external errors
- anyone / anything manipulating the DOM RE: validation errors

Are there any tasks an API consumer would be doing that is affected by validation but is not explicitly validation related?

**Comment by simonmarklar** [comment]
one thing I thought of - when a dev is hiding/showing form fields based on a fields value/validation state

eg if they hook into the blur event, and need to know the validation status at that time.

but i think for that scenario they can set a listener for the finished validation event. And if we document the change in a changelog then the devs using will (if they read them) know about it, and can change code appropriately. 

so i guess that https://github.com/blinkmobile/forms/blob/develop/docs/errors.md should be updated to reflect the changes?

**Comment by jokeyrhyme** [comment]
Agreed. There's definitely some documentation additions that need to be made, at the very least.

Also, those test helpers probably need to be promoted to core if we expect API consumers to be jumping through similar hoops.

**Comment by jokeyrhyme** [comment]
I'm also contemplating trying to break this up into multiple PRs (especially the "(chore) ..." stuff). I'm concerned that this might not be getting reviews (despite multiple calls for it) because it is too big.

**Comment by jokeyrhyme** [comment]
Closing this for now, as I think it can and should be broken up into smaller, more-atomic PRs.

**Pull request closed without merging**
