### PR TITLE
FORMS-193 # Added confirmation pop up on sub form removal and updated…

### PR DESCRIPTION
**Pull request by simonmarklar**
- add base popup class
- add confirmation pop up
- add Typed Errors
- fix tests to not rely on DOM manipulation to remove subforms

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Is there still at least one test somewhere that confirms that buttons in the DOM call the expected methods in the Backbone View? I generally like the idea of the tests looking cleaner, but I just want to double-check that our bases are covered.

**Comment by simonmarklar** [comment]
there was one, but it involved random timeouts, one to wait for the popup to show, one to wait for a button to be clicked. It was too fragile for my likes. 

I just thought of a way to test it that could be a bit cleaner, i'll try and implement and see how it goes

**Comment by jokeyrhyme** [comment]
Even just mocking to confirm that all the craziness in the DOM results in a button with a correct event handler would be sufficient.

**Comment by simonmarklar** [comment]
ok I added tests for the add/remove buttons on a sub form and the cancel/confirm buttons on the resulting pop up. I used timeouts :(

**Comment by jokeyrhyme** [comment]
Have we had a customer advocate give this a quick UX review?

**Pull request merged**
