### PR TITLE
FORMS-258 # GO/Return button click trigger camera and signature button events on ios.

### PR DESCRIPTION
**Pull request by GeetaSajwan**
- fixed for camera and signature button
- tested only for signature button
- couldn't reproduce with delete button of sub form record.

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
LGTM :+1: 

I usually like to keep HTML templates in a format that is XML parseable (e.g. self-closing `<input />`) for consistency with the way it's done in stricter frameworks, but this isn't a real problem here. Just something the bear in mind.

**Comment by simonmarklar** [comment]
LGTM too :+1:

**Comment by jokeyrhyme** [comment]
This Issue was pulled out of the review column. I think it's in the process of being re-worked.

**Comment by jokeyrhyme** [comment]
For PRs that have multiple commits, can you please use commit messages that describe what each commit does? Alternatively, you could squash these 8 commits down into 1. It's just a bit confusing for review purposes when there are 8 identical commit messages.

Do keep the JIRA Issue prefix at the beginning though, what you are already doing there is very helpful.

See these other PRs for examples of what more-helpful commit messages look like:
- https://github.com/blinkmobile/forms/pull/61
- https://github.com/blinkmobile/forms/pull/42

**Comment by simonmarklar** [comment]
out of interest, why has `test/31_subforms_collapse/definitions.js` been changed but the associated tests have not?

**Comment by GeetaSajwan** [comment]
They were testarea and i need text for my testing purpose. This change was not affecting any test.

**Comment by simonmarklar** [comment]
cool :+1:

**Comment by GeetaSajwan** [comment]
reviewed by rachel and ray

**Comment by jokeyrhyme** [comment]
Please resolve the merge conflicts. :)

**Comment by jokeyrhyme** [comment]
LGTM :+1:

**Pull request merged**
