### PR TITLE
FORMS-241 # Handle Chrome User Media Deprecations

### PR DESCRIPTION
**Pull request by simonmarklar**
- Refactor the Webcam element to uncouple the popup functionality from the button
- Make sure we are not using deprecated functions and properties
- Make it so the the future MediaDevice API can be implemented easier

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Great stuff here. I like that you've left space for the fallback (the seemingly unnecessary abstraction did throw me for a second). And templates are good. :)

Is it feasible to have tests for this functionality? Bearing in mind that we do have tests for geolocation (which causes a browser permission pop-up, which I'm guessing is the yucky part).

**Comment by simonmarklar** [comment]
yeah i was thinking about tests over the last couple of days. i had isolated tests we were talking about in mind when writing this, so each file should be able to have its dependencies mocked and tested, so i should be able to test the view and model by using the `_models` and `_views` property

**Comment by simonmarklar** [comment]
Added model and some view tests

**Comment by jokeyrhyme** [comment]
LGTM :+1:

**Comment by simonmarklar** [comment]
UX review from rachel

**Pull request merged**
