### PR TITLE
FORMS-237 # datetime/time with picker/native has broken model-view binding

### PR DESCRIPTION
**Pull request by GeetaSajwan**
- for datetime, set date to 0000-00-00 in case time has valid value
- for datetime, set time to 00:00 in case date has valid value
- created tests to confirm binding.

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
I don’t know whether this should be attempted within the current work, but having “magic” values like 0000-00-00 and 00:00 can be problematic. That’s a real date and real time that one-day someone will want to use, but it’ll break because we have assigned special purposes for those values.

Ideally, we shouldn't have any code that checks for "0000-00-00" or "00:00". The complete value is either valid or invalid, without special treatment of certain values.

I think it makes sense for a date+time field that has a date but no time (e.g. `2015-01-01T`), to automatically set the time part to 00:00. Automatically setting an empty time part to some value like this might help the user, especially if they don't care about the time part.

I don't think there's any valid assumption we can make about a date+time field that has a time but no date (e.g. `T12:34`).

I wonder if date, time and date+time views shouldn't send _anything_ to the model unless it's complete?
That'll mean that the model will stay empty, failing REQUIRED validation if any, right up until the user puts in a completely valid value. And it means we wouldn't need to check for "0000-00-00" or "00:00" during validation.

What do you think?

**Comment by simonmarklar** [comment]
LGTM

tests look like they cover the issue.

working with date and times is always painful :O

I actually think it would be easier if we had separate models and views for date, time, datetime as they are separate concepts, however that is not the focus of this ticket, and I dont know if the definition we use would allow for this... food for thought

**Comment by simonmarklar** [comment]
why not null instead of the magic values?

there could be a problem with time of 00:00 for time but i think we'd be safe with 0000-00-00 for date

**Comment by jokeyrhyme** [comment]
Yeah, I was mostly thinking out loud about ideals and purity. I don't think it's necessary to eliminate magic values within the scope of this Issue. I do think it's important to identity such magic values and get people thinking about alternatives.

LGTM :+1:

**Pull request merged**
