### PR TITLE
Forms-210 # Unable to access the Gallery from the iOS app, and image data broken

### PR DESCRIPTION
**Pull request by ashishtilara**
- Wrong name for cordova.PictureSourceType variable name
- PictureSourceType will be undefined in catch so just assign blank object
- Needs to be tested in app-shell or mBaas

Forms # Camera Button is not being rendered on browser
- attach button to correct element
- added tests to confirm the buttons are there

FORMS # set default attribute values

### CODE REVIEW

**Comment by simonmarklar** [comment]
LGTM

**Comment by jokeyrhyme** [comment]
LGTM :+1: 
For future reference, I find `Array#forEach()` makes for a nice built-in alternative to `_.each()`. :)

**Comment by jokeyrhyme** [comment]
Has a customer advocate taken a look at this yet?

**Comment by ashishtilara** [comment]
UX reviewed by Rachel

**Pull request merged**
